spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://13.125.0.54:3306/guitar
    username: guitar
    password: guitar
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 40

  redis:
    host: 13.125.0.54
    port: 6379

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: 295713f06b7aac58d9a5aa67cab86532c4a9a29afd1565491ad2242e1f950a12

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8081
#  address: 0.0.0.0

autocomplete:
  limit: 10
  suffix: "_suffix"
  key: "autocomplete"
  score-key: "autocomplete:score"